export function getRandomCarName() {
  const manufacturer = [
    'Audi',
    'Alfa Romeo',
    'Alpina',
    'Aston Martin',
    'Axon',
    'Ford',
    'Ferrari',
    'Fiat',
    'GAZ',
    'GMC',
    'Honda',
    'Hummer',
    'Hyundai',
    'Infiniti',
    'Isuzu',
    'JAC',
    'Jaguar',
    'Jeep',
    'Kamaz',
    'Lada',
    'Lexus',
    'Lotus',
    'MAN',
    'Maybach',
    'MAZ',
    'Mazda',
    'McLaren',
    'Nissan',
    'Opel',
    'Paccar',
    'Pagani',
    'Pontiac',
    'Porsche',
    'Renault',
    'Skoda',
    'Smart',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'UAZ',
    'Volvo',
    'ZAZ',
    'XPeng',
    'TVR',
    'Saab',
    'RAM',
    'Chevrolet',
    'Mazzanti',
    'Daewoo',
  ]
  const model = [
    'Roadster',
    'S',
    'X',
    '3',
    'Y',
    'Cybertruck',
    'X5',
    'X7',
    'X3',
    'X6',
    'GT4',
    'FXX',
    '599 GTO',
    'Enzo',
    '458 Italia',
    '250 GTO',
    'Priora',
    '4x4',
    'Rio',
    'Focus',
    'Kalina',
    'Vesta',
    'Spark',
    'Lacetti',
    'Nexia',
    'Matiz',
    'Cobalt',
    'Captiva',
    'A7',
    'A5',
    'A3',
    'A8',
    'TT',
    'Corolla',
    'Camry',
    'RAV4',
    'Impreza',
    'WRX',
    'ES',
    'LS',
    'RX',
    'GX',
    'LX',
    'GS',
    'LC500',
    'Gallardo',
    'Aventador',
    '911',
    'Cayenne',
    'FX37',
  ]
  return `${manufacturer[manufacturer.length * Math.random() | 0]} ${model[model.length * Math.random() | 0]}`
}

export function getRandomHexColor() {
  return `#${Math.floor(Math.random() * 16777215).toString(16)}`;
}
